# Generated by Django 2.1 on 2019-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPassword', models.CharField(max_length=20)),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
    ]
